### ISSUE TITLE
SPI begin() usage does not follow Arduino API

### ISSUE THREAD

**Issue by fpistm** [stm32duino/X-NUCLEO-53L8A1#2]
Hi @cparata 
it seems the library does not follows the standard Arduino SPI API as the `CS_PIN` is passed to `begin()`

https://github.com/stm32duino/X-NUCLEO-53L8A1/blob/89e0493d16b9b458e46075c24e9bebf05ad62c41/examples/X_NUCLEO_53L8A1_HelloWorld_SPI/X_NUCLEO_53L8A1_HelloWorld_SPI.ino#L86

https://github.com/stm32duino/X-NUCLEO-53L8A1/blob/89e0493d16b9b458e46075c24e9bebf05ad62c41/examples/X_NUCLEO_53L8A1_MultiSensorRanging_SPI/X_NUCLEO_53L8A1_MultiSensorRanging_SPI.ino#L88

https://github.com/stm32duino/X-NUCLEO-53L8A1/blob/89e0493d16b9b458e46075c24e9bebf05ad62c41/examples/X_NUCLEO_53L8A1_ThresholdDetection_SPI/X_NUCLEO_53L8A1_ThresholdDetection_SPI.ino#L94

Since I've aligned the API, the library cannot build.
https://github.com/stm32duino/Arduino_Core_STM32/pull/2171

Anyway without this change, I think the CS_PIN is not required here as the VL53L8CX library manage itself the CS pin
https://github.com/stm32duino/VL53L8CX/blob/7656f3dbe704aa7d40383bde1a877918613317aa/src/platform.cpp#L131C19-L134

**Comment by cparata** [comment]
Fixed in release 1.0.1
